### ISSUE TITLE
Download and Globe buttons not showing

### ISSUE THREAD

**Issue by Kano3D** [JackDesBwa/PhereoRoll3D#1]
First of all congratulations and thank you very much for developing this App. Users of my website tridimensional.info spoke to me about your App, it was precisely what I was looking for. It works perfectly on the 3D screen of my ZTE Axon 7 Max, my PPTV King 7S and my Doogee Y6 Max 3D (I suggest to put that on description so users of these devices can find this App -I will publish your App on my website and on a Stereoscopic AppStore, if you want-). PhereoRoll3D doesn't work in the 3D screen of SuperD D1 nor Takee 1 (we don't know the 3D screen format). 

Let's speak about the small bug. One user of my website reports that PhereoRoll3D doesn't show the Download button on images, nor the Globe button on his Elephone P8 3D. On my Doogee Y6 Max 3D I can see the globe icon, but I can't find the download button, so it has to be a small issue. On other devices I tested both buttons are shown and work properly.

Speaking of 3D Apps... Maybe you can develop a 3D YouTube App too, to play SBS 3D videos on column interlaced 3D smartphones..

**Comment by JackDesBwa** [comment]
**Answers to forewords:**

Thanks to have translated your issue into English, it is far easier to read for most people (including myself).

Your suggestion about listing some compatible devices is good (although might be time consuming). I created a form to gather compatibility data. Please add your models (and those of your readers) in the list: https://framaforms.org/phereoroll3d-compatibility-1547403883

The app is primary targeted to my ELEPHONE P8 3D and I share it as is. I added a few alternative display modes because it was quite easy to do while benefiting to several devices which are not supported by official phereo application, but I do not plan to support any devices. If someone cares, it can provide patches to improve the publicly available source code (either by doing it himself or by paying a freelancer to do so).

If the phones you mentioned use active barrier that has to be enabled by software, they will not work unless you can activate the barrier outside of the app itself; or if someone provide a patch to this app for those models.

I have no plan to develop other apps, and if I do, it will be for my own usage too.

You can share the app if you want. If you write an article about it, I'll be happy to review it before publication (see my profile for private contact).

**Answers about bug:**

**Globe:**
I am surprised about the absence of globe/web button and cannot imagine a cause of it (especially because it is the same model I use), except if it has a old version where this was not present (this button was added in v0.6).

**Download:** 
I will probably change the way this button works because it seems that there is a widespread inability to read a manual. In v0.5 and v0.6, the button appears only if the app is able to write to the picture folder, so you have to add storage access permission. I suppose that depending on the version of Android, it is enforced (old versions) or optional (new versions).

Feel free to reopen this issue if I misunderstood.

**Comment by JackDesBwa** [comment]
@Kano3D I just saw that you pushed this app on aptoid. But I have to warn you that the APK that you can download on this website is not the same as the official release.
The easiest way to see it is to compare their weight: the aptoid version weights about 15MB more!!! I do not know why they alter the content, but personally I would worry a lot about the related security issues. Thus I strongly advice you to change the way you run your app store to avoid their services knowing that they have such questionable practices.

**Comment by Kano3D** [comment]
That's the apk of the store, once installed you can download the original apk of the Apps
EDIT: Remove email reply garbage

**Comment by JackDesBwa** [comment]
OK, the "download" button is thus very misleading. Also with this method, man cannot check the integrity of the file and therefore I would not give any trust on it neither.
